theme: minima
title: My Python Projects [Kaif Kutchwala]
author: Kaif Kutchwala
email: kaifkutchwala@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is an open-to-all collection of the projects I have undertaken. 
  Feel free to use these as references or for the purpose they are made to serve!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Kaif-Kutchwala

show_excerpts: true # set to false to remove excerpts on the homepage
